### ISSUE TITLE
[課題2-7] np.linalg.norm()の利用

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [kaz-i-54/lab_tasks_for_newcommer#1]
以下のあたり、 `np.linalg.norm()` が使えそう。

https://github.com/kaz-i-54/lab_tasks_for_newcommer/blob/49900c792e1bb6a80fd777464700d70ff57cf6f8/02_protein/m2_7.py#L14-L15

**Comment by edge2992** [comment]
np.linalg.norm()を利用しました
