### ISSUE TITLE
課題4 Ridge回帰にもStandardScaler()が必要

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [kaz-i-54/lab_tasks_for_newcommer#10]
Ridge回帰の正則化項は、記述子に対する重みwに対して機能します。
しかし、例えばある記述子が100倍になって、予測すべき値が変化しなければ重みwは単純計算で100分の1になるので、Ridge回帰の正則化が効きにくくなります。（詳細は機械学習の書籍などを参照してください）。
そんなわけで、Ridge回帰にもStandardScaler()などを適用させてください。

**Comment by edge2992** [comment]
https://github.com/kaz-i-54/lab_tasks_for_newcommer/blob/master/04_chem/m4_6/regression.py

grid_many内でStandardScalerを適用するようなパイプラインを作成しています

**Comment by keisuke-yanagisawa** [comment]
あー、なるほど、そっちでは対応されてるのですね。柳澤は課題4-5を見てコメントしてました。すみません。

**Comment by edge2992** [comment]
jupyterノーブックの方は柳澤先生に機械学習の参考書をお借りする前に書いたコードなのでいろいろ間違っているかもしれないです

**Comment by keisuke-yanagisawa** [comment]
りょかいです！

**Comment by edge2992** [comment]
正則化が効きにくくなるというのは考えていなかったので、あ、なるほど...と思いました。ありがとうございます

**Comment by keisuke-yanagisawa** [comment]
ちなみにRandom Forestの分類（たぶん回帰も？）は正規化の必要はないのですが、それはなぜか？を考えるのも、勉強になるかも、と思いましたー。

**Comment by keisuke-yanagisawa** [comment]
コメントだけだったのでcloseしました。
