### ISSUE TITLE
c was defined but not used

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [kaz-i-54/lab_tasks_for_newcommer#2]
https://github.com/kaz-i-54/lab_tasks_for_newcommer/blob/49900c792e1bb6a80fd777464700d70ff57cf6f8/02_protein/m2_8.py#L6

**Comment by edge2992** [comment]
```
PyMOL>centerofmass chain A
 Center of Mass: [  47.038,  33.340,  35.567]
PyMOL>center chain A
PyMOL>get_position
 cmd.get_position: [  47.026,  33.322,  35.562]
```

center chain A とした時に移動する場所とcenterofmass chian Aの座標が異なるので、cの位置を中心とする必要があるようですが、座標の扱いが難しいです...

**Comment by keisuke-yanagisawa** [comment]
恐らく、centerofmassは重心なので原子量を考慮していて、centerは原子量を考慮せずに中心を求めている？のだと思いますー。調べてないで物事言ってるけど。。。

**Comment by keisuke-yanagisawa** [comment]
（水素原子はどう処理されているんだろう…もしかしたらcenterは水素原子は考慮せずに計算しているかも）

**Comment by edge2992** [comment]
cを利用して、centerofmassを中心座標として処理しました
