### ISSUE TITLE
[課題1-3] 図のrefinement

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [kaz-i-54/lab_tasks_for_newcommer#3]
- [x] x軸、y軸のラベルを明示する。
- [x] この図をスライドにペタっと貼ったとしても見えるくらいまでフォントサイズを大きくする

上記2つは秋山先生が最低限求めるポイントなので、今のうちにやる習慣をつけておきましょ！

**Comment by edge2992** [comment]
- [x]  x軸、y軸のラベルを明示する。
- [x] この図をスライドにペタっと貼ったとしても見えるくらいまでフォントサイズを大きくする

**Comment by keisuke-yanagisawa** [comment]
GC含量 0.150 (%) は嘘では 🤔 ｗ
たぶん割合だと思うので、それだけ修正しておいてください…笑

**Comment by edge2992** [comment]
アッ...

**Comment by edge2992** [comment]
修正しました
