### ISSUE TITLE
[課題3-2] なんか結果がヘン？？

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [kaz-i-54/lab_tasks_for_newcommer#4]
README.mdには以下のように書かれている。が、roc_auc最適化しているはずの上段のauc scoreよりもf1最適化している下段のauc scoreの方が高い。

```
==================roc_auc==================  
{'C': 50, 'gamma': 0.2}  
precision score of test set: 0.98077  
recall score of test set: 0.91071  
auc score of test set: 0.96429  
matthews_corrcoef score of test set: 0.86047  
f score of test set: 0.94444  
==================f1==================  
{'C': 50, 'gamma': 0.1}  
precision score of test set: 0.94340  
recall score of test set: 0.92593  
auc score of test set: 0.97495  
matthews_corrcoef score of test set: 0.83339  
f score of test set: 0.93458  
```

**Comment by edge2992** [comment]
==================roc_auc==================
roc_auc
{'C': 50, 'gamma': 0.2}
precision score of test set: 0.94828
recall score of test set: 0.93220
auc score of test set: 0.98422
matthews_corrcoef score of test set: 0.82182
f score of test set: 0.94017
==================f1==================
f1
{'C': 50, 'gamma': 0.1}
precision score of test set: 0.93651
recall score of test set: 0.96721
auc score of test set: 0.94961
matthews_corrcoef score of test set: 0.83758
f score of test set: 0.95161


GridSearchCVで求めたパラメーターは変わりませんが、testケースによって（？）結果が大きくブレるようです。
流れとして、
1.grid()関数でGridSearchCVでパラメータを求める。
2.そのパラメータでテストケースと学習ケースに分けたものを再度学習させてスコアを出すようにしています。（一覧のスコアを見るため）

**Comment by keisuke-yanagisawa** [comment]
あーー、あーーーー、なんか色々わかってきました。。。が結構説明する事項が多くてどうしようかな。slackでご連絡します。

**Comment by keisuke-yanagisawa** [comment]
#6 にコメントしておきました。コードの変更自体は確認したのでこのissueは閉じてしまいます。
