### ISSUE TITLE
[課題3-2] sklearn.model_selection.GridSearchCV() がオススメ

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [kaz-i-54/lab_tasks_for_newcommer#5]
GridSearchCV() という、今回の目的にとても合致したモノが存在するので、こちらの利用をお勧めします。

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

**Comment by edge2992** [comment]
grid関数内でGridSearchCVを利用しています

**Comment by keisuke-yanagisawa** [comment]
見落としてましたすみません。。。

別の問題を勘違いしていたので、別issueにします
