### ISSUE TITLE
[課題3-2]C, gammaは指数的にパラメータサーチする

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [kaz-i-54/lab_tasks_for_newcommer#6]
parameterの探索なのですが、Cやgammaは一般的に指数的にパラメータサーチを行います。

https://github.com/kaz-i-54/lab_tasks_for_newcommer/blob/6e1a9621f337e7b164e92e09a1084e4e8a745205/03_learning/m3_2.py#L69-L72

### 参考資料
「Python機械学習プログラミング 達人データサイエンティストによる理論と実践」の書籍に関するコードがgithubに上がっているので、そこから当該部分へのリンクをはっておきます。
https://github.com/rasbt/python-machine-learning-book-2nd-edition/blob/b96dd315986d3f30fd893c130550b7990c5035a0/code/ch06/ch06.py#L465-L480

**Comment by edge2992** [comment]
データセットをまずテストとトレインに分けて、トレインでグリッドサーチしたモデルを使ってテストでスコアを出しました。README.mdに結果を記載したのですが、安定せず、おそらく過学習によりf1, aucが逆転したりします。

**Comment by keisuke-yanagisawa** [comment]
状況を確認しました。2つ原因が考えられますね・・・ただ、このコードならいちゃもんを付けられることは無いと思います。

原因について、簡単に解説しておきます。結論から言えば、どちらも「仕方がない」ものなので、問題ありません。

### ① ValidationとTestでデータ集合が違うので多少結果が変わる
まぁあたりまえの話なのですが、ValidationデータセットとTestデータセットは異なるデータセットなので、予測結果が異なります。

さらに言うと、Validationデータセットのscoreが最大になるようにハイパーパラメータを決めるので、**Validation score > Test score** という関係になることが一般的です（だからTestデータセットを作る必要があったんですね）。ちなみにこれは過学習とは言わず…名前はついていない気がします。

### ② GridSearchCVの特徴的な挙動によるもの
GridSearchCVは、

1. データ集合をTraining-Validationに分割しながら（ここcross-validation）、ハイパーパラメータを決める
2. データ集合を**分割せず**に、1で決めたハイパーパラメータを使って学習する

という処理を行っています。なので、作られたモデルってcross-validation中に作られたもののどれでもありません。（誰も知らない）最適なハイパーパラメータがcross-validationで推定されたものと異なる可能性も全然あります。

学習時に使えるデータが多いほど予測精度は高くなるだろう、ということで、これはTestデータに対する予測を行う際には適切なのですが、この挙動を理解していないと、変な所でハマります（①で述べた Validation score > Test score の関係にならなくて悩むとか）。

**Comment by keisuke-yanagisawa** [comment]
上記の事項、理解したー、と思ったらissue閉じてしまってください。お願いします。
