### ISSUE TITLE
[課題1-3] GC含有量の値がやけに低い？

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [kaz-i-54/lab_tasks_for_newcommer#8]
ぼくもしっかりと正答例を持っていないのですが、全域でGC含量がそんなに低いか・・・？という気持ちになっています。ランダムなら50%あるはず…。コードにバグがないかチェックする必要がありそう。

**Comment by keisuke-yanagisawa** [comment]
あっ…バグみつけました…

https://github.com/kaz-i-54/lab_tasks_for_newcommer/blob/29d7ac6f0f42a489e60b3f701ed79afe2e96625e/01_dna/m1_3.py#L15

**Comment by edge2992** [comment]
確かに低いなと思っていました。widに訂正しました
