### ISSUE TITLE
[課題4-8] 予測が「膜透過しやすい側」に間違っているのか、「膜透過しにくい側」に間違っているのか見てみる

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [kaz-i-54/lab_tasks_for_newcommer#9]
現在は「絶対値が大きくことなる」ものを全てbadとして表示しているが、過大評価される分子と過小評価される分子の傾向は違う気がする。
それらを分けて図にするか、図に実測＆予測値を示してみる。

**Comment by edge2992** [comment]
図にして、予測のハズレに関係がある特徴量を抽出しようとしました。
予測値＞実験値・予測値＝実験値、予測値＜実験値の３つにラベルをつけてクラス分類の精度から特徴量を抽出しようとしたのですが、あまりうまく行きませんでした。
ラベルが偏っているので評価関数の選定が難しかったです。

**Comment by keisuke-yanagisawa** [comment]
ちょっとionization stateで分類してみましたが、確かに一筋縄ではいかなさそうかなーという印象。
負に帯電（カルボニルとかだろうけど）している子たちが、実測値＜予測値 と膜透過を過大評価されていることが多いように見えるので、ちょっとそれは気になるかなぁ、、、？
あと正に帯電している（アミン？）分子の中でも、予測がうまくいくものとうまく行かないものの違いとか？
![image](https://user-images.githubusercontent.com/6902135/81490338-380b6800-92bc-11ea-84fa-7cfff08fd336.png)

**Comment by keisuke-yanagisawa** [comment]
まぁ、この課題としての要求しているレベルはすでに超えている気がするので、やらなくてもOKです！
